name: Build Application

on:
  push:
    branches: [main, feature/*]
      
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GTIHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-action-bot <support+action@github.com>"
        env:         
          GTIHUB_TOKEN: ${{ secrets.GTIHUB_TOKEN }}
          
         
